// Sample data. In a real app this would come from an API.
export const events = [
  {
    id: 'git-github-basics',
    name: 'Git and GitHub for Beginners',
    date: '2026-10-17',
    time: '4:00 PM to 6:00 PM',
    category: 'Workshop',
    mode: 'On campus',
    location: 'Lab 3, CS Block',
    organizer: 'Open Source Cell',
    description: 'Learn commits, branches and pull requests by pushing your first project to GitHub, step by step.',
    tags: ['git', 'github', 'beginner'],
  },
  {
    id: 'c-pointers-clinic',
    name: 'C Pointers Clinic',
    date: '2026-10-21',
    time: '5:00 PM to 6:30 PM',
    category: 'Meetup',
    mode: 'On campus',
    location: 'Seminar Hall 2',
    organizer: 'Systems Study Circle',
    description: 'Bring your doubts about pointers, arrays and memory. Seniors will walk through diagrams and live examples.',
    tags: ['c', 'pointers', 'memory'],
  },
  {
    id: 'genai-prompt-to-prototype',
    name: 'Prompt to Prototype with Generative AI',
    date: '2026-10-24',
    time: '10:00 AM to 1:00 PM',
    category: 'Workshop',
    mode: 'On campus',
    location: 'Innovation Lab',
    organizer: 'AI Club',
    description: 'Turn an idea into a working prototype using prompts and an AI coding assistant, then learn to review what it wrote.',
    tags: ['ai', 'generative ai', 'prototype'],
  },
  {
    id: 'campus-hack-48',
    name: 'Campus Hack 48',
    date: '2026-11-07',
    time: '10:00 AM Saturday to 10:00 AM Sunday',
    category: 'Hackathon',
    mode: 'On campus',
    location: 'Main Auditorium',
    organizer: 'Student Tech Council',
    description: 'Form a team of up to four and build a solution for a campus problem in 24 hours. Mentors available throughout.',
    tags: ['hackathon', 'teams', 'build'],
  },
  {
    id: 'flutter-study-jam',
    name: 'Flutter Study Jam',
    date: '2026-11-14',
    time: '11:00 AM to 2:00 PM',
    category: 'Workshop',
    mode: 'Online',
    location: 'Google Meet',
    organizer: 'Mobile Dev Group',
    description: 'Build a simple mobile app from scratch and learn how widgets, state and layouts fit together.',
    tags: ['flutter', 'mobile', 'dart'],
  },
  {
    id: 'alumni-panel',
    name: 'Careers in Tech: Alumni Panel',
    date: '2026-11-19',
    time: '6:00 PM to 7:30 PM',
    category: 'Talk',
    mode: 'On campus',
    location: 'Main Auditorium',
    organizer: 'Placement Cell',
    description: 'Four alumni share how they got their first tech role, what they wish they had learned earlier, and answer your questions.',
    tags: ['careers', 'alumni', 'internships'],
  },
  {
    id: 'figma-ui-basics',
    name: 'UI Design Basics with Figma',
    date: '2026-11-28',
    time: '2:00 PM to 5:00 PM',
    category: 'Workshop',
    mode: 'On campus',
    location: 'Design Studio',
    organizer: 'Design Club',
    description: 'Learn layout, spacing and colour, then design a mobile app screen you can hand over to a developer.',
    tags: ['figma', 'ui', 'design'],
  },
  {
    id: 'web-dev-sprint',
    name: 'Web Dev Sprint',
    date: '2026-12-05',
    time: '9:00 AM to 6:00 PM',
    category: 'Hackathon',
    mode: 'On campus',
    location: 'Computer Centre',
    organizer: 'Web Dev Group',
    description: 'A one-day frontend challenge. Build and deploy a responsive web app and present it to a panel of judges.',
    tags: ['frontend', 'html', 'css', 'javascript'],
  },
  {
    id: 'cloud-basics',
    name: 'Cloud Basics for Beginners',
    date: '2026-12-12',
    time: '3:00 PM to 5:00 PM',
    category: 'Workshop',
    mode: 'Online',
    location: 'Zoom',
    organizer: 'Cloud Study Group',
    description: 'Understand servers, storage and deployment, then put a small website online using a free hosting plan.',
    tags: ['cloud', 'deployment', 'hosting'],
  },
  {
    id: 'open-source-day',
    name: 'Open Source Contribution Day',
    date: '2026-12-19',
    time: '10:00 AM to 4:00 PM',
    category: 'Meetup',
    mode: 'On campus',
    location: 'Lab 1, CS Block',
    organizer: 'Open Source Cell',
    description: 'Pick a beginner-friendly issue, make your first contribution and get a review from experienced contributors.',
    tags: ['open source', 'git', 'contribution'],
  },
  {
    id: 'python-showcase',
    name: 'Python Mini Projects Showcase',
    date: '2027-01-09',
    time: '4:00 PM to 6:00 PM',
    category: 'Meetup',
    mode: 'On campus',
    location: 'Seminar Hall 1',
    organizer: 'Python Users Group',
    description: 'First-years and seniors demo small Python projects. Great place to get ideas and find teammates.',
    tags: ['python', 'projects', 'demo'],
  },
  {
    id: 'ai-ethics-chat',
    name: 'AI and Ethics: A Fireside Chat',
    date: '2027-01-16',
    time: '5:00 PM to 6:30 PM',
    category: 'Talk',
    mode: 'Online',
    location: 'Google Meet',
    organizer: 'AI Club',
    description: 'A faculty member and an industry engineer discuss bias, privacy and responsible use of AI tools.',
    tags: ['ai', 'ethics', 'privacy'],
  },
];

// Pretends to be a network request so we can show a loading state.
export function fetchEvents() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(events), 700);
  });
}
